# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/goppy',
                'doc_host': 'https://galicae.github.io',
                'git_url': 'https://github.com/galicae/goppy',
                'lib_path': 'goppy'},
  'syms': { 'goppy.core': { 'goppy.core.plot_synteny': ('core.html#plot_synteny', 'goppy/core.py'),
                            'goppy.core.plot_synteny_schematic': ('core.html#plot_synteny_schematic', 'goppy/core.py')},
            'goppy.util': { 'goppy.util.decorate': ('util.html#decorate', 'goppy/util.py'),
                            'goppy.util.estimate_plot_size': ('util.html#estimate_plot_size', 'goppy/util.py'),
                            'goppy.util.filter': ('util.html#filter', 'goppy/util.py'),
                            'goppy.util.gff_attribute_selector': ('util.html#gff_attribute_selector', 'goppy/util.py'),
                            'goppy.util.read_aln': ('util.html#read_aln', 'goppy/util.py'),
                            'goppy.util.read_gff': ('util.html#read_gff', 'goppy/util.py'),
                            'goppy.util.syntenic_block_borders': ('util.html#syntenic_block_borders', 'goppy/util.py')}}}
