# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/goppy',
                'doc_host': 'https://galicae.github.io',
                'git_url': 'https://github.com/galicae/goppy',
                'lib_path': 'goppy'},
  'syms': {'goppy.core': {'goppy.core.foo': ('core.html#foo', 'goppy/core.py')}}}
